CREATE TABLE "User" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" varchar(255),
  "password_hash" varchar(255),
  "first_name" varchar(255),
  "last_name" varchar(255),
  "birthday" date,
  "nationalID" varchar(255),
  "created_at" timestamp,
  "updated_at" timestamp,
  "status" varchar(50)
);

CREATE TABLE "Role" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" varchar
);

CREATE TABLE "User_Role" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "role_id" bigint
);

CREATE TABLE "PatientProfile" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "patient_number" varchar,
  "blood_group" varchar,
  "initial_bp" integer,
  "initial_spo2" integer,
  "initial_heartrate" integer,
  "ward" varchar,
  "bed_number" varchar,
  "visitor_pass_id" bigint
);

CREATE TABLE "DoctorProfile" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "doctor_number" varchar,
  "specialization" varchar,
  "qualifications" text,
  "registration_number" varchar,
  "department" varchar
);

CREATE TABLE "StaffProfile" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" bigint,
  "staff_number" varchar,
  "job_title" varchar,
  "department" varchar
);

CREATE TABLE "VisitorPass" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "patient_id" bigint,
  "pass_code" varchar,
  "max_visitors" integer,
  "created_at" timestamp,
  "expires_at" timestamp
);

ALTER TABLE "User_Role" ADD FOREIGN KEY ("user_id") REFERENCES "User" ("id");

ALTER TABLE "User_Role" ADD FOREIGN KEY ("role_id") REFERENCES "Role" ("id");

ALTER TABLE "User" ADD FOREIGN KEY ("id") REFERENCES "PatientProfile" ("user_id");

ALTER TABLE "User" ADD FOREIGN KEY ("id") REFERENCES "DoctorProfile" ("user_id");

ALTER TABLE "User" ADD FOREIGN KEY ("id") REFERENCES "StaffProfile" ("user_id");

ALTER TABLE "VisitorPass" ADD FOREIGN KEY ("patient_id") REFERENCES "PatientProfile" ("id");
